source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '10.0'

use_frameworks!
target 'DWDebugHR' do
    
    pod 'GCDWebServer/WebUploader', '~> 3.0'    # 本地server

end
